version: '3'

services:
  php:
    environment:
      COMPOSER_PROCESS_TIMEOUT: 1200
      PHP_IDE_CONFIG: serverName=phpstorm
      # Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
      PHP_XDEBUG_MAX_NESTING_LEVEL: 256
      # Standard activated.
      PHP_XDEBUG_IDEKEY: "phpstorm"
      PHP_XDEBUG_START_WITH_REQUEST: "yes"
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
