version: "3"

services:

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1
      # Linux correct permission files.
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby

  nginx:
    environment:
      # Linux correct permission files.
      NGINX_USER: wodby

  apache:
    environment:
      # Linux correct permission files.
      APACHE_USER: wodby
      APACHE_GROUP: wodby
